<?php 
namespace  common\web\util\Codes;
        /**
         *@AUTHOR: Prachi         
         *@REASON: use code instead of id  
         */
class LookupTypeCodes{
CONST LT_USER_ROLES = 1;
CONST LT_USER_TYPE = 2;
CONST LT_APP_CONFIGURATIONS = 3;
CONST LT_SYSTEM_OPERATIONS = 4;
CONST LT_DEVICETYPE = 5;
CONST LT_SOCIAL_LOGINS = 6;
CONST LT_EMAIL_STATUS = 7;
CONST LT_GENDER = 8;
CONST LT_MARITAL_STATUS = 9;
CONST LT_COMMON_STATUS = 10;
CONST LT_PERMISSION_TYPES = 11;
CONST LT_AUTO_GENERATE = 14;
CONST LT_CONFIGURATION_SECTION = 15;
CONST LT_MAIL_METHOD = 16;
CONST LT_DEVICE_TOKEN_OPTIONS = 17;
CONST LT_EMAIL_TEMPLATES = 18;
CONST LT_USER_STATUS = 19;
CONST LT_LANGUGAGE = 20;
CONST LT_DISPLAY_DATE_FORMAT = 21;
CONST LT_MULTIPLE_DEVICE_OPTIONS = 22;
CONST LT_CMS_CATEGORY = 23;
CONST LT_CMS_SUB_CATEGORY = 24;
CONST LT_CMS_LAYOUT = 25;
CONST LT_CMS_CHILD_CATEGORY = 26;
CONST LT_CMS_FOURTH_SUB_CAT = 27;
CONST LT_PERMISSION_DISPLAY_OPTIONS = 28;
CONST LT_E_MAIL_SENDER = 29;
CONST LT_PUSH_NOTIFICATION_SCREEN = 30;
CONST LT_NOTIFICATION_TYPE = 32;
CONST LT_USER_VERIFICATION = 33;
CONST LT_USER_VERIFICATION_METHOD = 34;
}
?>
